version: '3'
services:
    web:
        restart: always
        build:
            context: .
            args:
                DEBUG: ${DEBUG}
        command: bash entrypoint.sh
        ports:
            - 8000:8000
        networks:
            - external_network
            - internal_network
        depends_on:
            - db
        env_file:
            - .env
    db:
        image: postgres:14-alpine
        shm_size: 256mb
        networks:
            - internal_network
            - external_network
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres']
        volumes:
            - ./postgres14:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - 'POSTGRES_HOST_AUTH_METHOD=trust'


networks:
    external_network:
    internal_network:
        internal: true
