# Generated by Django 4.1.2 on 2022-10-23 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comercial', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cnpj', models.CharField(max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('localidade', models.CharField(max_length=100)),
                ('validade_passaporte', models.DateField()),
                ('bio', models.TextField()),
                ('qnt_criancas', models.IntegerField()),
                ('recebe_consolidado_vagas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatou_se', models.BooleanField(default=False)),
                ('aupair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.aupair')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('qnt_filhos', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('e_prioritaria', models.BooleanField(default=False)),
                ('data_renovacao', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('detalhes', models.TextField()),
                ('agencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.agencia')),
                ('au_pair_contratado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.aupair')),
                ('candidaturas', models.ManyToManyField(related_name='candidaturas', through='bases.Candidatura', to='bases.aupair')),
                ('caracteristicas', models.ManyToManyField(to='bases.caracteristica')),
                ('familia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.familia')),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.vaga'),
        ),
        migrations.AddField(
            model_name='aupair',
            name='caracteristicas',
            field=models.ManyToManyField(to='bases.caracteristica'),
        ),
        migrations.AddField(
            model_name='aupair',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
